# adapted from https://github.com/rdkit/rdkit-tutorials/blob/master/.travis.yml

language: python
python:
  - "3.5"

# switch to new infrastructure
sudo: false

before_install:
  # download and install miniconda
  - wget http://repo.continuum.io/miniconda/Miniconda3-4.1.11-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/conda
  - export PATH="$HOME/conda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  # create and activate the build/test environment
  - conda create -q -n tenv python=$TRAVIS_PYTHON_VERSION pip cmake
  - source activate tenv

install:
  - conda install -c openbabel openbabel
  - pip install PyYAML
  - conda install pandas
  - conda install -q -c rdkit rdkit
  - conda install -c anaconda pytest
  - python setup.py install
  - conda install -c conda-forge progress
  - pip install pytest-cov codecov
  - pip install Cython --install-option="--no-cython-compile"
  - pip install ase
  - pip install --pre torch torchvision -f https://download.pytorch.org/whl/nightly/cu100/torch_nightly.html
  - pip install torchani
  - pip install goodvibes

before_script:
  - export RDBASE=$CONDA_PREFIX/Library/share/RDKit
  - echo $RDBASE

script:
  - cd tests
  - pytest -v --cov=pyconfort
  - codecov
